routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'App\Http\Controllers\Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'App\Http\Controllers\Auth\LoginController@login');

Route::get('register', 'App\Http\Controllers\Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'App\Http\Controllers\Auth\RegisterController@register');

Route::middleware('auth')->group(function() {
    Route::get('', 'App\Http\Controllers\DashboardController@index');
    Route::get('dashboard', 'App\Http\Controllers\DashboardController@index');
    Route::get('logout', 'App\Http\Controllers\Auth\UserLoginController@logout')->name('user.logout');

    Route::get('imgur/search/{term?}', 'App\Http\Controllers\ImgurSearchController@index');

    Route::resource('wishlists', 'App\Http\Controllers\WishlistController');
    Route::resource('wishlists/{wishlist}/items', 'App\Http\Controllers\WishlistItemController');
    Route::resource('wishlists/{wishlist}/shares', 'App\Http\Controllers\WishlistShareController')->only('create', 'store', 'destroy');

    Route::get('shared-wishlists/buy-item/{wishlistItem}', 'App\Http\Controllers\SharedWishlistsController@buyItem');
    Route::get('shared-wishlists/view-item/{wishlistItem}', 'App\Http\Controllers\SharedWishlistsController@viewItem');
    Route::resource('shared-wishlists', 'App\Http\Controllers\SharedWishlistsController')->only('index', 'show');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function wishlists()
    {
        return $this->hasMany(Wishlist::class);
    }

    public function sharedWishlists()
    {
        return $this->belongsToMany(Wishlist::class, 'wishlist_shares');
    }
}

resources/views/user/shared/index.blade.php
@extends('layouts.app')

@section('title')
    Shared Wishlists
@endsection

@section('content')
    @if(count($wishlistShares))
        <table class="table">
            <thead>
            <tr>
                <th scope="col" width="10%">#</th>
                <th scope="col" width="45%">Name</th>
                <th scope="col" width="25%">Shared By</th>
                <th scope="col" width="20%">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($wishlistShares as $wishlistShare)
                <tr id="listtr-{{ $wishlistShare->wishlist->id }}">
                    <th scope="row">{{ $loop->iteration }}</th>
                    <td>{{ $wishlistShare->wishlist->name }}</td>
                    <td>{{ $wishlistShare->wishlist->user->name }}</td>
                    <td>
                        <a href="{{ url('shared-wishlists/'.$wishlistShare->wishlist->slug) }}">
                            <button type="button" class="btn btn-primary btn-sm">View</button>
                        </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @else
        <p class="fs-5 text-muted text-center">You don't have any shared wishlists.</p>
    @endif
@endsection

resources/views/user/shared/show.blade.php
@extends('layouts.app')

@section('title')
    View Shared Wishlist - {{ $wishlist->name }}
@endsection

@section('content')
    @if(count($wishlist->items))
        <table class="table">
            <thead>
            <tr>
                <th scope="col" width="10%">#</th>
                <th scope="col" width="40%">Name</th>
                <th scope="col" width="15%">Price</th>
                <th scope="col" width="15%">Is bought by me</th>
                <th scope="col" width="20%">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($wishlist->items as $wishlistItem)
                <tr class="{{ $wishlistItem->is_bought ? 'red-bg' : 'green-bg' }}">
                    <th scope="row">{{ $loop->iteration }}</th>
                    <td>{{ $wishlistItem->name }}</td>
                    <td>{{ $wishlistItem->price }}</td>
                    <td>{{ $wishlistItem->bought_by == auth()->user()->id ? 'Yes' : '' }}</td>
                    <td>
                        @if(!$wishlistItem->is_bought)
                            <a href="{{ url('shared-wishlists/view-item/'.$wishlistItem->id) }}">
                                <button type="button" class="btn btn-primary btn-sm">View Item</button>
                            </a>
                            <a href="{{ url('shared-wishlists/buy-item/'.$wishlistItem->id) }}">
                                <button type="button" class="btn btn-success btn-sm">I will buy this</button>
                            </a>
                        @endif
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @else
        <p class="fs-5 text-muted text-center">No wishlist items found.</p>
    @endif
@endsection

resources/views/user/shared/viewItem.blade.php
@extends('layouts.app')

@section('title')
    View Shared Wishlist Item
@endsection

@section('content')
    <div class="mt-3">
        <label>Name</label>
        <h4>{{ $wishlistItem->name }}</h4>
    </div>
    <div class="mt-3">
        <label>Description</label>
        <h5>{{ $wishlistItem->description }}</h5>
    </div>
    <div class="mt-3">
        <label>Price</label>
        <h5>{{ $wishlistItem->price }}</h5>
    </div>
    <div class="mt-3">
        <label>Where to buy</label>
        <h5>{{ $wishlistItem->url ?? '' }}</h5>
    </div>
    <div class="mt-3">
        <label>Image</label>
        @if(!empty($wishlistItem->image))
            <div class="mb-3">
                <label for="image" class="form-label">Existing Image</label><br/>
                <div class="row">
                    <div class="col-lg-4 col-md-6">
                        <img src="{{ $wishlistItem->image }}" class="imgur-preview" alt="preview image"/>
                    </div>
                </div>
            </div>
        @endif
    </div>
    <div class="mt-3">
        <a href="{{ url('shared-wishlists/buy-item/' . $wishlistItem->id) }}">
            <button type="button" class="btn btn-success">I will buy this</button>
        </a>
        <a href="{{ route('shared-wishlists.show', $wishlistItem->wishlist->slug) }}">
            <button type="button" class="btn btn-primary">Back</button>
        </a>
    </div>
@endsection