routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'App\Http\Controllers\Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'App\Http\Controllers\Auth\LoginController@login');

Route::get('register', 'App\Http\Controllers\Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'App\Http\Controllers\Auth\RegisterController@register');

Route::middleware('auth')->group(function() {
    Route::get('', 'App\Http\Controllers\DashboardController@index');
    Route::get('dashboard', 'App\Http\Controllers\DashboardController@index');
    Route::get('logout', 'App\Http\Controllers\Auth\UserLoginController@logout')->name('user.logout');

    Route::get('imgur/search/{term?}', 'App\Http\Controllers\ImgurSearchController@index');

    Route::resource('wishlists', 'App\Http\Controllers\WishlistController');
    Route::resource('wishlists/{wishlist}/items', 'App\Http\Controllers\WishlistItemController');
    Route::resource('wishlists/{wishlist}/shares', 'App\Http\Controllers\WishlistShareController')->only('create', 'store', 'destroy');

    Route::get('shared-wishlists/buy-item/{wishlistItem}', 'App\Http\Controllers\SharedWishlistsController@buyItem');
    Route::get('shared-wishlists/view-item/{wishlistItem}', 'App\Http\Controllers\SharedWishlistsController@viewItem');
    Route::resource('shared-wishlists', 'App\Http\Controllers\SharedWishlistsController')->only('index', 'show');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function wishlists()
    {
        return $this->hasMany(Wishlist::class);
    }

    public function sharedWishlists()
    {
        return $this->belongsToMany(Wishlist::class, 'wishlist_shares');
    }
}

app/Models/Wishlist.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Wishlist extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'name',
        'slug'
    ];

    public function items()
    {
        return $this->hasMany(WishlistItem::class);
    }

    public function shares()
    {
        return $this->hasMany(WishlistShare::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/WishlistController.php
<?php

namespace App\Http\Controllers;

use App\Http\Middleware\CheckIfWishlistBelongsToLoggedUser;
use App\Http\Requests\Wishlist\CreateWishlistRequest;
use App\Http\Requests\Wishlist\UpdateWishlistRequest;
use App\Http\Responses\SuccessMessageResponse;
use App\Interfaces\WishlistItemRepositoryInterface;
use App\Interfaces\WishlistRepositoryInterface;
use App\Models\Wishlist;
use Illuminate\Http\Response;

class WishlistController extends Controller
{
    private WishlistRepositoryInterface $wishlistRepository;
    private WishlistItemRepositoryInterface $wishlistItemRepository;

    public function __construct(WishlistRepositoryInterface $wishlistRepository, WishlistItemRepositoryInterface $wishlistItemRepository)
    {
        $this->wishlistRepository = $wishlistRepository;
        $this->wishlistItemRepository = $wishlistItemRepository;
        $this->middleware(CheckIfWishlistBelongsToLoggedUser::class)->except('index');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $wishlists = $this->wishlistRepository->getWishlistsForUser(auth()->user()->id);
        return view('user.wishlists.index', ['wishlists' => $wishlists]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('user.wishlists.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateWishlistRequest $request
     * @return Response
     */
    public function store(CreateWishlistRequest $request)
    {
        $data = array_merge($request->validated(), ['user_id' => auth()->user()->id]);
        $this->wishlistRepository->createWishlist($data);
        return redirect('wishlists');
    }

    /**
     * Display the specified resource.
     *
     * @param Wishlist $wishlist
     * @return Response
     */
    public function show(Wishlist $wishlist)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Wishlist $wishlist
     * @return Response
     */
    public function edit(Wishlist $wishlist)
    {
        $wishlist->load('shares.user');
        $wishlistItems = $this->wishlistItemRepository->getWishlistItems($wishlist->id);
        return view('user.wishlists.edit', ['wishlist' => $wishlist, 'wishlistItems' => $wishlistItems]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateWishlistRequest $request
     * @param int $id
     * @return Response
     */
    public function update(UpdateWishlistRequest $request, $id)
    {
        $this->wishlistRepository->updateWishlist($id, $request->validated());
        return redirect(route('wishlists.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Wishlist $wishlist
     * @return Response
     */
    public function destroy(Wishlist $wishlist)
    {
        $this->wishlistRepository->deleteWishlist($wishlist->id);
        return SuccessMessageResponse::return('Item deleted');
    }
}

resources/views/user/wishlists/create.blade.php
@extends('layouts.app')

@section('title')
    Create Wishlist
@endsection

@section('content')
    <form class="form-horizontal" method="POST" action="{{ url('wishlists') }}">
        {{ csrf_field() }}
        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name">
            @if ($errors->has('name'))
                <span class="help-block">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
            @endif
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/user/wishlists/edit.blade.php
@extends('layouts.app')

@section('title')
    Edit Wishlist
@endsection

@section('content')
    <ul class="nav nav-tabs" id="myTab">
        <li class="nav-item">
            <a href="#settings" class="nav-link active" data-bs-toggle="tab">Settings</a>
        </li>
        <li class="nav-item">
            <a href="#items" class="nav-link" data-bs-toggle="tab">Items</a>
        </li>
        <li class="nav-item">
            <a href="#shares" class="nav-link" data-bs-toggle="tab">Shares</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active pt-5" id="settings">
            <form class="form-horizontal" method="POST" action="{{ route('wishlists.update', $wishlist->id) }}">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="put"/>
                <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" class="form-control" id="name" name="name" value="{{ $wishlist->name }}">
                    @if ($errors->has('name'))
                        <span class="help-block">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
                    @endif
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{{ route('wishlists.index') }}">
                    <button type="button" class="btn btn-success">Back</button>
                </a>
            </form>
        </div>
        <div class="tab-pane fade pt-5" id="items">
            @if(count($wishlistItems))
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col" width="10%">#</th>
                        <th scope="col" width="25%">Name</th>
                        <th scope="col" width="40%">Description</th>
                        <th scope="col" width="10%">Price</th>
                        <th scope="col" width="15%">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($wishlistItems as $wishlistItem)
                        <tr id="listtr-{{$wishlistItem->id}}">
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td>{{ $wishlistItem->name }}</td>
                            <td>{{ $wishlistItem->description }}</td>
                            <td>{{ $wishlistItem->price }}</td>
                            <td>
                                <a href="{{ route('items.edit', [$wishlist->id, $wishlistItem->id]) }}">
                                    <button type="button" class="btn btn-primary btn-sm">Edit</button>
                                </a>
                                <button type="button" class="btn btn-danger btn-sm deleteitem"
                                        data-wishlistId="{{ $wishlist->id }}"
                                        data-wishlistItemId="{{ $wishlistItem->id }}"
                                        data-token="{{csrf_token()}}">Delete
                                </button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="d-flex justify-content-center">
                    {!! $wishlistItems->fragment('items')->render() !!}
                </div>
            @else
                <p class="fs-5 text-muted text-center">You don't have any wishlist items.</p>
            @endif
            <a href="{{ route('items.create', $wishlist->id) }}">
                <button type="button" class="btn btn-success">Create Wishlist Item</button>
                <a href="{{ route('wishlists.index') }}">
                    <button type="button" class="btn btn-success">Back</button>
                </a>
            </a>
        </div>
        <div class="tab-pane fade pt-5" id="shares">
            <h4 class="mt-2">Shares</h4>
            <p>Share would consider as accepted once the email that it's sent to exists in the Users table.</p>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col" width="10%">#</th>
                    <th scope="col" width="50%">Email</th>
                    <th scope="col" width="20%">Accepted</th>
                    <th scope="col" width="20%">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($wishlist->shares as $share)
                    <tr id="listtr-{{ $share->id }}">
                        <th scope="row">{{ $loop->iteration }}</th>
                        <td>{{ $share->user->email ?? $share->email }}</td>
                        <td>{{ !empty($share->user) ? 'Yes' : 'No' }}</td>
                        <td>
                            <button type="button" class="btn btn-danger btn-sm deleteshare"
                                    data-wishlistid="{{ $wishlist->id }}"
                                    data-id="{{ $share->id }}"
                                    data-token="{{csrf_token()}}">Delete
                            </button>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            <a href="{{ route('shares.create', $wishlist->id) }}">
                <button type="button" class="btn btn-primary">Create Wishlist Share</button>
            </a>
            <a href="{{ route('wishlists.index') }}">
                <button type="button" class="btn btn-success">Back</button>
            </a>

        </div>
    </div>
@endsection

@section('customjs')
    <script src="{{asset('js/user/wishlists.js')}}"></script>
    <script src="{{asset('js/user/wishlistItems.js')}}"></script>
@stop

resources/views/user/wishlists/index.blade.php
@extends('layouts.app')

@section('title')
    My Wishlists
@endsection

@section('content')
    @if(count($wishlists))
        <table class="table">
            <thead>
            <tr>
                <th scope="col" width="10%">#</th>
                <th scope="col" width="70%">Name</th>
                <th scope="col" width="20%">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($wishlists as $wishlist)
                <tr id="listtr-{{ $wishlist->id }}">
                    <th scope="row">{{ $loop->iteration }}</th>
                    <td>{{ $wishlist->name }}</td>
                    <td>
                        <a href="{{ url('wishlists/'.$wishlist->id.'/edit') }}">
                            <button type="button" class="btn btn-primary btn-sm">Edit</button>
                        </a>
                        @csrf
                        @method('DELETE')
                        <button type="button" class="btn btn-danger btn-sm deletewishlist"
                                data-id="{{ $wishlist->id }}"
                                data-token="{{csrf_token()}}">Delete
                        </button>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @else
        <p class="fs-5 text-muted text-center">You don't have any wishlists.</p>
    @endif
    <a href="{{ url('wishlists/create') }}">
        <button type="button" class="btn btn-success">Create Wishlist</button>
    </a>
@endsection

@section('customjs')
    <script src="{{asset('js/user/wishlists.js')}}"></script>
@stop